# doctesting untuk testing python
# jika pull request fail dengan python testing
# akan di review oleh contributor
# jika tidak ada perubahan maka pull request akan ditutup

name: python testing
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test Python
      run: |
        pytest . --doctest-modules
    - name: Test Lint Python
      run: |
        flake8 . --ignore=E203, W503 --max-complexity=25 --max-line-length=88